"""Service layer for deterministic PV scenario execution and Dash integration."""

from .config_metadata import extract_config_metadata, update_config_table_values
from .export_artifacts import export_deterministic_artifacts, export_risk_artifacts
from .export_excel import export_comparison_workbook, export_scenario_workbook
from .io_excel import ensure_template, load_config_from_excel, load_example_config, rebuild_config_bundle
from .result_views import (
    build_comparison_figures,
    build_comparison_table,
    build_session_comparison_rows,
    resolve_selected_candidate_key_for_scenario,
)
from .risk_views import prepare_risk_views
from .i18n import tr
from .risk_registry import clear_expired_risk_results, clear_risk_results, get_risk_result, store_risk_result
from .risk_ui import (
    build_risk_candidate_options,
    build_risk_metadata_rows,
    build_risk_result_store_payload,
    prepare_percentile_table_for_display,
    ready_risk_scenarios,
    resolve_default_risk_candidate,
    resolve_default_risk_scenario,
    validate_risk_run_inputs,
)
from .scenario_runner import run_scan, run_scenario
from .scenario_session import (
    add_scenario,
    create_scenario_record,
    default_scenario_name,
    delete_scenario,
    duplicate_scenario,
    rename_scenario,
    run_scenario_scan,
    set_active_scenario,
    set_comparison_scenarios,
    update_scenario_bundle,
    update_selected_candidate,
)
from .stochastic_runner import MONTE_CARLO_WARNING_THRESHOLD, run_monte_carlo, summarize_monte_carlo
from .types import (
    LoadedConfigBundle,
    MetricDistributionSummary,
    MonteCarloRunRequest,
    MonteCarloRunResult,
    MonteCarloSummary,
    PercentileSummary,
    RiskMetricSummary,
    RiskViewBundle,
    ScanRunResult,
    ScenarioRecord,
    ScenarioRunResult,
    ScenarioSessionState,
    ValidationIssue,
)
from .ui_schema import build_assumption_sections, build_display_columns, format_metric, metric_help, metric_label
from .validation import (
    normalize_battery_catalog_rows,
    normalize_inverter_catalog_rows,
    refresh_bundle_issues,
    validate_config,
)
from .workbench_ui import (
    collect_config_updates,
    demand_profile_visibility,
    frame_from_rows,
    rebuild_bundle_from_ui,
    workbench_status_message,
)

__all__ = [
    "LoadedConfigBundle",
    "MetricDistributionSummary",
    "MONTE_CARLO_WARNING_THRESHOLD",
    "MonteCarloRunRequest",
    "MonteCarloRunResult",
    "MonteCarloSummary",
    "PercentileSummary",
    "RiskMetricSummary",
    "RiskViewBundle",
    "ScanRunResult",
    "ScenarioRecord",
    "ScenarioRunResult",
    "ScenarioSessionState",
    "ValidationIssue",
    "build_assumption_sections",
    "add_scenario",
    "build_comparison_figures",
    "build_comparison_table",
    "build_display_columns",
    "build_risk_candidate_options",
    "build_risk_metadata_rows",
    "build_risk_result_store_payload",
    "build_session_comparison_rows",
    "clear_expired_risk_results",
    "clear_risk_results",
    "create_scenario_record",
    "default_scenario_name",
    "delete_scenario",
    "demand_profile_visibility",
    "duplicate_scenario",
    "ensure_template",
    "export_deterministic_artifacts",
    "export_comparison_workbook",
    "export_risk_artifacts",
    "export_scenario_workbook",
    "extract_config_metadata",
    "format_metric",
    "frame_from_rows",
    "get_risk_result",
    "load_config_from_excel",
    "load_example_config",
    "metric_help",
    "metric_label",
    "normalize_battery_catalog_rows",
    "normalize_inverter_catalog_rows",
    "prepare_percentile_table_for_display",
    "prepare_risk_views",
    "ready_risk_scenarios",
    "rebuild_bundle_from_ui",
    "rebuild_config_bundle",
    "refresh_bundle_issues",
    "rename_scenario",
    "resolve_default_risk_candidate",
    "resolve_default_risk_scenario",
    "resolve_selected_candidate_key_for_scenario",
    "run_monte_carlo",
    "run_scan",
    "run_scenario",
    "run_scenario_scan",
    "set_active_scenario",
    "set_comparison_scenarios",
    "store_risk_result",
    "summarize_monte_carlo",
    "tr",
    "update_config_table_values",
    "update_scenario_bundle",
    "update_selected_candidate",
    "validate_config",
    "validate_risk_run_inputs",
    "workbench_status_message",
    "collect_config_updates",
]
